<pre> 
<div class="container form-group col-md-6" align="center">
    Conteúdo: <input class="form-control" type="text" name="txtCon"><br>
    <input type="radio" name="txtAno" value="N" checked> Me identificar<br>
    <input type="radio" name="txtAno" value="S"> Não me identificar<br>
    <input class="btn btn-outline-success btn-block btn-lg" type="submit" value="Enviar" name="btn"><br>
</div>
</pre>