<pre> 
<div class="container form-group col-md-6" align="center">
    Remetente: <input class="form-control" type="text" name="txtRem" value="<?php echo $nome ?>" disabled><br> 
    Conteúdo: <input class="form-control" type="text" name="txtCon"><br>
    Anonimato: <input class="form-control" type="text" name="txtAno"><br>
    <input class="btn btn-outline-success btn-block btn-lg" type="submit" value="Enviar" name="btn"><br>
</div>
</pre>